name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload frontend build files
        uses: actions/upload-artifact@v3
        with:
          name: frontend-files
          path: ./frontend/dist # Path to frontend build output

      - name: Upload admin build files
        uses: actions/upload-artifact@v3
        with:
          name: admin-files
          path: ./admin/dist # Path to admin build output

      - name: Upload backend build files
        uses: actions/upload-artifact@v3
        with:
          name: backend-files
          path: ./backend/dist # Path to backend build output

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-files
          path: ./dist/frontend # Path to where frontend artifact will be downloaded

      - name: Download admin artifact
        uses: actions/download-artifact@v3
        with:
          name: admin-files
          path: ./dist/admin # Path to where admin artifact will be downloaded

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-files
          path: ./dist/backend # Path to where backend artifact will be downloaded

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Path to all downloaded artifacts
